// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFOW9vy4iAGofbYxuFsuO6TKRZPaEFfgM',
    appId: '1:399689529420:web:65044879fbb5ae3930dce9',
    messagingSenderId: '399689529420',
    projectId: 'ditonton-18e73',
    authDomain: 'ditonton-18e73.firebaseapp.com',
    storageBucket: 'ditonton-18e73.appspot.com',
    measurementId: 'G-FVN6WPQQ8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf90_xeOZ63mZP-ADxWTdP6hFessG4FPY',
    appId: '1:399689529420:android:626cb6e832c109d030dce9',
    messagingSenderId: '399689529420',
    projectId: 'ditonton-18e73',
    storageBucket: 'ditonton-18e73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-gbEiXk5Z9SLxQcl-cEXL3CQS527UQ0w',
    appId: '1:399689529420:ios:960f9cc30ab81b3d30dce9',
    messagingSenderId: '399689529420',
    projectId: 'ditonton-18e73',
    storageBucket: 'ditonton-18e73.appspot.com',
    iosClientId: '399689529420-es0e6rm8u10j40tpg8buhe7vh2qpkgsf.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
